# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/sdlc-lib-makefiles.js
#####

SDLC_SDLC_LIB_MAKEFILES_JS:=$(DIST)/sdlc-lib-makefiles.js
SDLC_SDLC_LIB_MAKEFILES_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_SDLC_LIB_MAKEFILES_JS)

$(SDLC_SDLC_LIB_MAKEFILES_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_SDLC_LIB_MAKEFILES_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/sdlc-lib-makefiles.js
#####
